In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("ner_dataset.csv", encoding="latin1")

In [3]:
data.head()

    Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [4]:
# Calculating Initial Probabilites

inital_prob_df = data.Tag.value_counts()
inital_prob_df = pd.DataFrame(inital_prob_df)
inital_prob_df['initial_porb'] = inital_prob_df.Tag/inital_prob_df.Tag.sum()
inital_prob_df

          Tag  initial_porb
O      887908      0.846776
B-geo   37644      0.035900
B-tim   20333      0.019391
B-org   20143      0.019210
I-per   17251      0.016452
B-per   16990      0.016203
I-org   16784      0.016006
B-gpe   15870      0.015135
I-geo    7414      0.007071
I-tim    6528      0.006226
B-art     402      0.000383
B-eve     308      0.000294
I-art     297      0.000283
I-eve     253      0.000241
B-nat     201      0.000192
I-gpe     198      0.000189
I-nat      51      0.000049

In [5]:
# Creating Transition Matrix
transition_mat = pd.DataFrame(columns=inital_prob_df.Tag.keys(), index=inital_prob_df.Tag.keys())
transition_mat

,O,B-geo,B-tim,B-org,I-per,B-per,I-org,B-gpe,I-geo,I-tim,B-art,B-eve,I-art,I-eve,B-nat,I-gpe,I-nat
O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B-geo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B-tim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B-org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I-per,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B-per,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I-org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B-gpe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I-geo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I-tim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B-art,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B-eve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I-art,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I-eve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B-nat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I-gpe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I-nat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Adding i+1 Tag value as a new Column

temp_df = data.Tag.iloc[1:]
temp_df_cast_list = list(temp_df)
temp_df_cast_list.append(np.nan)

In [7]:
len(temp_df_cast_list)

1048575

In [8]:
len(data)

1048575

In [9]:
data['Next_Tag'] = temp_df_cast_list
data.head(10)

    Sentence #           Word  POS    Tag Next_Tag
0  Sentence: 1      Thousands  NNS      O        O
1          NaN             of   IN      O        O
2          NaN  demonstrators  NNS      O        O
3          NaN           have  VBP      O        O
4          NaN        marched  VBN      O        O
5          NaN        through   IN      O    B-geo
6          NaN         London  NNP  B-geo        O
7          NaN             to   TO      O        O
8          NaN        protest   VB      O        O
9          NaN            the   DT      O        O

In [10]:
data.head(100)

     Sentence #           Word  POS    Tag Next_Tag
0   Sentence: 1      Thousands  NNS      O        O
1           NaN             of   IN      O        O
2           NaN  demonstrators  NNS      O        O
3           NaN           have  VBP      O        O
4           NaN        marched  VBN      O        O
5           NaN        through   IN      O    B-geo
6           NaN         London  NNP  B-geo        O
7           NaN             to   TO      O        O
8           NaN        protest   VB      O        O
9           NaN            the   DT      O        O
10          NaN            war   NN      O        O
11          NaN             in   IN      O    B-geo
12          NaN           Iraq  NNP  B-geo        O
13          NaN            and   CC      O        O
14          NaN         demand   VB      O        O
15          NaN            the   DT      O        O
16          NaN     withdrawal   NN      O        O
17          NaN             of   IN      O    B-gpe
18          NaN        British   JJ  B-gpe        O
19          NaN         troops  NNS      O        O
20          NaN           from   IN      O        O
21          NaN           that   DT      O        O
22          NaN        country   NN      O        O
23          NaN              .    .      O        O
24  Sentence: 2       Families  NNS      O        O
25          NaN             of   IN      O        O
26          NaN       soldiers  NNS      O        O
27          NaN         killed  VBN      O        O
28          NaN             in   IN      O        O
29          NaN            the   DT      O        O
..          ...            ...  ...    ...      ...
70          NaN            the   DT      O        O
71          NaN         number   NN      O        O
72          NaN             of   IN      O        O
73          NaN       marchers  NNS      O        O
74          NaN             at   IN      O        O
75          NaN         10,000   CD      O        O
76          NaN          while   IN      O        O
77          NaN     organizers  NNS      O        O
78          NaN        claimed  VBD      O        O
79          NaN             it  PRP      O        O
80          NaN            was  VBD      O        O
81          NaN       1,00,000   CD      O        O
82          NaN              .    .      O        O
83  Sentence: 5            The   DT      O        O
84          NaN        protest   NN      O        O
85          NaN          comes  VBZ      O        O
86          NaN             on   IN      O        O
87          NaN            the   DT      O        O
88          NaN            eve   NN      O        O
89          NaN             of   IN      O        O
90          NaN            the   DT      O        O
91          NaN         annual   JJ      O        O
92          NaN     conference   NN      O        O
93          NaN             of   IN      O    B-geo
94          NaN        Britain  NNP  B-geo        O
95          NaN             's  POS      O        O
96          NaN         ruling  VBG      O    B-org
97          NaN          Labor  NNP  B-org    I-org
98          NaN          Party  NNP  I-org        O
99          NaN             in   IN      O        O

[100 rows x 5 columns]

In [11]:
sent_index = data[data['Sentence #'].notnull()].index
sent_index

Int64Index([      0,      24,      54,      68,      83,     108,     132,
                153,     181,     196,
            ...
            1048375, 1048400, 1048422, 1048438, 1048472, 1048501, 1048521,
            1048545, 1048556, 1048567],
           dtype='int64', length=47959)

In [12]:
# Substracing -1 from the recived indexes.
def substract_non_zero(lst):
    res = []
    for item in lst:
        if item == 0:
            res.append(item)
            continue
        else:
            res.append(item-1)
    return res

sent_index_above = []
sent_index_above = substract_non_zero(sent_index)

In [16]:
sent_index_above

[0,
 23,
 53,
 67,
 82,
 107,
 131,
 152,
 180,
 195,
 220,
 232,
 266,
 295,
 321,
 361,
 371,
 393,
 427,
 447,
 471,
 494,
 523,
 548,
 580,
 594,
 617,
 636,
 655,
 680,
 687,
 716,
 738,
 763,
 789,
 824,
 854,
 875,
 909,
 919,
 940,
 967,
 986,
 1021,
 1050,
 1074,
 1098,
 1124,
 1134,
 1143,
 1166,
 1188,
 1226,
 1265,
 1279,
 1296,
 1316,
 1340,
 1371,
 1393,
 1402,
 1417,
 1424,
 1448,
 1482,
 1490,
 1531,
 1557,
 1591,
 1623,
 1644,
 1651,
 1668,
 1682,
 1711,
 1732,
 1762,
 1800,
 1822,
 1836,
 1860,
 1890,
 1910,
 1928,
 1953,
 1964,
 1981,
 2001,
 2022,
 2051,
 2065,
 2093,
 2117,
 2137,
 2164,
 2171,
 2205,
 2217,
 2249,
 2274,
 2306,
 2319,
 2335,
 2353,
 2366,
 2394,
 2403,
 2421,
 2439,
 2459,
 2471,
 2497,
 2507,
 2535,
 2567,
 2589,
 2609,
 2635,
 2656,
 2667,
 2701,
 2728,
 2742,
 2757,
 2781,
 2795,
 2829,
 2855,
 2873,
 2892,
 2915,
 2936,
 2960,
 2988,
 3001,
 3024,
 3046,
 3069,
 3087,
 3110,
 3148,
 3174,
 3189,
 3213,
 3238,
 3271,
 3296,
 3316,
 3352,
 3371,
 3380,
 3396,
 3416,
 3443,
 3447,
 3483,
 3507,
 3547,
 3579,
 3597,
 3618,
 3642,
 3653,
 3670,
 3681,
 3698,
 3726,
 3747,
 3762,
 3788,
 3802,
 3822,
 3839,
 3864,
 3892,
 3899,
 3920,
 3942,
 3952,
 3964,
 3984,
 3990,
 4000,
 4028,
 4045,
 4066,
 4107,
 4132,
 4151,
 4186,
 4209,
 4232,
 4249,
 4274,
 4292,
 4312,
 4339,
 4364,
 4382,
 4403,
 4431,
 4461,
 4481,
 4487,
 4518,
 4535,
 4565,
 4583,
 4610,
 4635,
 4650,
 4674,
 4685,
 4710,
 4736,
 4776,
 4793,
 4819,
 4849,
 4879,
 4908,
 4929,
 4951,
 4981,
 5002,
 5017,
 5031,
 5046,
 5068,
 5080,
 5102,
 5122,
 5149,
 5166,
 5193,
 5223,
 5249,
 5277,
 5301,
 5309,
 5330,
 5351,
 5366,
 5381,
 5408,
 5438,
 5472,
 5492,
 5510,
 5527,
 5540,
 5563,
 5573,
 5585,
 5599,
 5611,
 5617,
 5632,
 5661,
 5690,
 5722,
 5752,
 5782,
 5810,
 5825,
 5832,
 5843,
 5871,
 5886,
 5907,
 5939,
 5961,
 5985,
 6002,
 6018,
 6040,
 6056,
 6083,
 6109,
 6132,
 6154,
 6177,
 6200,
 6214,
 6238,
 6259,
 6276,
 6286,
 6312,
 6350,
 6379,
 6395,
 6418,
 6435,
 6446,
 6466,
 6477,
 6506,
 6525,
 6556,
 6578,
 6603,
 6623,
 6639,
 6665,
 6683,
 6705,
 6723,
 6738,
 6759,
 6781,
 6808,
 6839,
 6862,
 6887,
 6904,
 6924,
 6956,
 6979,
 7003,
 7032,
 7046,
 7072,
 7087,
 7108,
 7123,
 7152,
 7171,
 7183,
 7198,
 7217,
 7233,
 7245,
 7275,
 7302,
 7332,
 7378,
 7400,
 7423,
 7437,
 7464,
 7487,
 7511,
 7537,
 7551,
 7566,
 7588,
 7618,
 7645,
 7676,
 7694,
 7723,
 7749,
 7768,
 7783,
 7795,
 7815,
 7834,
 7853,
 7860,
 7869,
 7909,
 7936,
 7962,
 7976,
 7988,
 8000,
 8020,
 8056,
 8085,
 8106,
 8123,
 8142,
 8161,
 8176,
 8216,
 8245,
 8279,
 8313,
 8348,
 8367,
 8380,
 8405,
 8423,
 8450,
 8467,
 8497,
 8525,
 8548,
 8566,
 8575,
 8584,
 8598,
 8625,
 8657,
 8688,
 8704,
 8724,
 8750,
 8772,
 8782,
 8808,
 8831,
 8842,
 8867,
 8885,
 8898,
 8927,
 8954,
 8981,
 9025,
 9056,
 9082,
 9107,
 9121,
 9143,
 9154,
 9175,
 9206,
 9226,
 9242,
 9259,
 9292,
 9313,
 9323,
 9346,
 9359,
 9391,
 9419,
 9445,
 9481,
 9504,
 9513,
 9524,
 9542,
 9559,
 9587,
 9600,
 9619,
 9639,
 9660,
 9698,
 9714,
 9727,
 9736,
 9762,
 9774,
 9787,
 9807,
 9826,
 9866,
 9890,
 9921,
 9944,
 9950,
 9978,
 9992,
 10013,
 10033,
 10051,
 10074,
 10098,
 10120,
 10140,
 10176,
 10201,
 10214,
 10241,
 10251,
 10277,
 10292,
 10313,
 10325,
 10344,
 10361,
 10379,
 10397,
 10422,
 10446,
 10475,
 10504,
 10530,
 10554,
 10578,
 10603,
 10640,
 10674,
 10689,
 10704,
 10721,
 10740,
 10759,
 10780,
 10805,
 10822,
 10831,
 10856,
 10897,
 10922,
 10946,
 10975,
 11001,
 11023,
 11041,
 11053,
 11065,
 11086,
 11123,
 11141,
 11173,
 11197,
 11224,
 11236,
 11257,
 11283,
 11312,
 11329,
 11345,
 11363,
 11378,
 11400,
 11421,
 11447,
 11462,
 11493,
 11517,
 11542,
 11565,
 11573,
 11598,
 11625,
 11640,
 11672,
 11697,
 11721,
 11735,
 11764,
 11786,
 11809,
 11833,
 11861,
 11888,
 11908,
 11919,
 11940,
 11960,
 11993,
 12027,
 12060,
 12075,
 12095,
 12123,
 12140,
 12160,
 12178,
 12199,
 12216,
 12227,
 12254,
 12273,
 12297,
 12340,
 12364,
 12389,
 12409,
 12440,
 12471,
 12492,
 12534,
 12559,
 12586,
 12622,
 12635,
 12666,
 12693,
 12728,
 12747,
 12778,
 12792,
 12821,
 12834,
 12848,
 12875,
 12913,
 12954,
 12977,
 12991,
 13008,
 13034,
 13058,
 13097,
 13115,
 13133,
 13148,
 13167,
 13185,
 13201,
 13228,
 13241,
 13247,
 13269,
 13283,
 13294,
 13326,
 13358,
 13394,
 13423,
 13451,
 13513,
 13525,
 13571,
 13580,
 13595,
 13624,
 13653,
 13670,
 13687,
 13717,
 13747,
 13762,
 13793,
 13819,
 13847,
 13873,
 13902,
 13915,
 13934,
 13946,
 13970,
 13983,
 14007,
 14039,
 14066,
 14078,
 14090,
 14107,
 14146,
 14155,
 14181,
 14199,
 14238,
 14254,
 14270,
 14306,
 14329,
 14346,
 14370,
 14397,
 14415,
 14438,
 14478,
 14510,
 14535,
 14555,
 14576,
 14593,
 14612,
 14633,
 14643,
 14659,
 14688,
 14711,
 14738,
 14748,
 14763,
 14795,
 14810,
 14829,
 14849,
 14858,
 14869,
 14879,
 14891,
 14906,
 14940,
 14955,
 14975,
 14990,
 15005,
 15021,
 15041,
 15054,
 15081,
 15100,
 15121,
 15134,
 15151,
 15176,
 15216,
 15257,
 15279,
 15299,
 15310,
 15338,
 15364,
 15407,
 15437,
 15475,
 15503,
 15531,
 15541,
 15566,
 15602,
 15616,
 15625,
 15650,
 15664,
 15692,
 15712,
 15727,
 15748,
 15766,
 15776,
 15782,
 15812,
 15830,
 15862,
 15874,
 15894,
 15930,
 15960,
 15969,
 16003,
 16021,
 16045,
 16077,
 16109,
 16117,
 16150,
 16183,
 16207,
 16234,
 16264,
 16276,
 16308,
 16337,
 16362,
 16385,
 16408,
 16421,
 16440,
 16462,
 16484,
 16495,
 16507,
 16524,
 16545,
 16565,
 16582,
 16597,
 16629,
 16655,
 16674,
 16691,
 16720,
 16741,
 16761,
 16777,
 16802,
 16827,
 16854,
 16884,
 16916,
 16943,
 16965,
 16983,
 17014,
 17040,
 17050,
 17055,
 17077,
 17098,
 17122,
 17147,
 17185,
 17213,
 17225,
 17253,
 17280,
 17307,
 17325,
 17346,
 17363,
 17374,
 17396,
 17430,
 17451,
 17473,
 17503,
 17521,
 17548,
 17573,
 17610,
 17623,
 17666,
 17686,
 17712,
 17738,
 17769,
 17781,
 17805,
 17832,
 17857,
 17888,
 17920,
 17926,
 17951,
 17987,
 18023,
 18042,
 18070,
 18089,
 18108,
 18126,
 18135,
 18155,
 18178,
 18211,
 18234,
 18252,
 18280,
 18291,
 18322,
 18330,
 18357,
 18374,
 18389,
 18403,
 18429,
 18451,
 18480,
 18517,
 18543,
 18556,
 18587,
 18591,
 18611,
 18635,
 18659,
 18671,
 18680,
 18692,
 18713,
 18740,
 18771,
 18794,
 18818,
 18836,
 18850,
 18864,
 18887,
 18909,
 18920,
 18934,
 18950,
 18968,
 18981,
 19013,
 19031,
 19056,
 19083,
 19095,
 19116,
 19128,
 19144,
 19166,
 19191,
 19210,
 19229,
 19256,
 19276,
 19286,
 19311,
 19329,
 19357,
 19363,
 19377,
 19397,
 19425,
 19447,
 19471,
 19493,
 19524,
 19561,
 19577,
 19600,
 19613,
 19631,
 19653,
 19690,
 19711,
 19736,
 19764,
 19780,
 19810,
 19837,
 19867,
 19882,
 19893,
 19912,
 19954,
 19969,
 19990,
 20020,
 20054,
 20081,
 20102,
 20120,
 20129,
 20163,
 20188,
 20212,
 20240,
 20269,
 20292,
 20316,
 20333,
 20344,
 20351,
 20379,
 20405,
 20418,
 20451,
 20464,
 20483,
 20507,
 20528,
 20549,
 20581,
 20608,
 20620,
 20641,
 20656,
 20694,
 20712,
 20740,
 20755,
 20777,
 20793,
 20814,
 20837,
 20852,
 20874,
 20895,
 20918,
 20938,
 20953,
 20962,
 20975,
 20988,
 21008,
 21025,
 21042,
 21062,
 21102,
 21132,
 21160,
 21196,
 21213,
 21229,
 21261,
 21288,
 21303,
 21313,
 21324,
 21344,
 21368,
 21381,
 21416,
 21438,
 21451,
 21461,
 21485,
 21522,
 21548,
 21555,
 21566,
 21581,
 21595,
 21619,
 21636,
 21660,
 21690,
 21705,
 21722,
 21738,
 21752,
 21787,
 21812,
 21837,
 21865,
 21891,
 21925,
 21942,
 21964,
 21988,
 22011,
 22029,
 22053,
 22065,
 ...]

In [14]:
# adding column Index

data['Index'] = data.index

In [169]:
def rm_tag(row):
    if row['Index'] in sent_index_above:
        row['Next_Tag'] = np.nan
    return row

In [ ]:
data.apply(rm_tag, axis=1)

In [154]:
data.tail(100)

              Sentence #        Word  POS    Tag Next_Tag
1048475              NaN      pushed  VBD      O        O
1048476              NaN         the   DT      O    B-org
1048477              NaN     Taleban  NNP  B-org        O
1048478              NaN        from   IN      O        O
1048479              NaN       power   NN      O        O
1048480              NaN          in   IN      O    B-tim
1048481              NaN        2001   CD  B-tim        O
1048482              NaN           ,    ,      O        O
1048483              NaN         but   CC      O        O
1048484              NaN     members  NNS      O        O
1048485              NaN          of   IN      O        O
1048486              NaN         the   DT      O        O
1048487              NaN   extremist   NN      O        O
1048488              NaN       group   NN      O        O
1048489              NaN    continue  VBP      O        O
1048490              NaN          to   TO      O        O
1048491              NaN       fight   VB      O    B-gpe
1048492              NaN      Afghan   JJ  B-gpe        O
1048493              NaN         and   CC      O        O
1048494              NaN     foreign   JJ      O        O
1048495              NaN      forces  NNS      O        O
1048496              NaN   defending  VBG      O        O
1048497              NaN         the   DT      O    B-org
1048498              NaN       Kabul  NNP  B-org        O
1048499              NaN  government   NN      O        O
1048500              NaN           .    .      O    B-gpe
1048501  Sentence: 47955      Indian   JJ  B-gpe        O
1048502              NaN      border   NN      O        O
1048503              NaN    security   NN      O        O
1048504              NaN      forces  NNS      O        O
...                  ...         ...  ...    ...      ...
1048545  Sentence: 47957         Two   CD      O        O
1048546              NaN        more  JJR      O        O
1048547              NaN      landed  VBD      O        O
1048548              NaN          in   IN      O        O
1048549              NaN      fields  NNS      O        O
1048550              NaN   belonging  VBG      O        O
1048551              NaN          to   TO      O        O
1048552              NaN           a   DT      O        O
1048553              NaN      nearby   JJ      O        O
1048554              NaN     village   NN      O        O
1048555              NaN           .    .      O        O
1048556  Sentence: 47958        They  PRP      O        O
1048557              NaN         say  VBP      O        O
1048558              NaN         not   RB      O        O
1048559              NaN         all   DT      O        O
1048560              NaN          of   IN      O        O
1048561              NaN         the   DT      O        O
1048562              NaN     rockets  NNS      O        O
1048563              NaN    exploded  VBD      O        O
1048564              NaN        upon   IN      O        O
1048565              NaN      impact   NN      O        O
1048566              NaN           .    .      O    B-gpe
1048567  Sentence: 47959      Indian   JJ  B-gpe        O
1048568              NaN      forces  NNS      O        O
1048569              NaN        said  VBD      O        O
1048570              NaN        they  PRP      O        O
1048571              NaN   responded  VBD      O        O
1048572              NaN          to   TO      O        O
1048573              NaN         the   DT      O        O
1048574              NaN      attack   NN      O      NaN

[100 rows x 5 columns]

In [112]:
data.groupby(['Tag', 'Next_Tag'])['Word'].count()

Tag    Next_Tag
B-art  B-geo            1
       B-org            3
       B-per            1
       B-tim            6
       I-art          177
       O              214
B-eve  B-geo            1
       B-tim            4
       I-eve          173
       O              130
B-geo  B-art            2
       B-eve            1
       B-geo            3
       B-gpe          142
       B-org           57
       B-per          108
       B-tim          792
       I-geo         6643
       O            29896
B-gpe  B-art            1
       B-eve            1
       B-geo          134
       B-org          426
       B-per         1299
       B-tim           31
       I-gpe          190
       O            13788
B-nat  B-geo            1
       B-per            1
       B-tim            1
                    ...
I-org  B-geo           23
       B-gpe           43
       B-per          335
       B-tim          243
       I-org         7247
       O             8893
I-per  B-geo            4
       B-gpe            1
       B-org           19
       B-per            2
       B-tim          157
       I-per         4636
       O            12432
I-tim  B-eve           10
       B-geo           52
       B-gpe           13
       B-org           11
       B-per           15
       B-tim            1
       I-tim         1923
       O             4503
O      B-art          384
       B-eve          282
       B-geo        37092
       B-gpe        15451
       B-nat          198
       B-org        19205
       B-per        14830
       B-tim        18834
       O           781631
Name: Word, Length: 110, dtype: int64

In [17]:
data.iloc[21988, 4]=np.nan

In [18]:
data.iloc[21988, 4]

nan